name: "OpenVINO Whisper STT"
slug: "openvino_whisper"
description: "Intel OpenVINO accelerated Whisper STT"
version: "3.3.0"
arch:
  - amd64
startup: services
boot: auto
host_network: true
privileged: true
devices:
  - /dev/dri:/dev/dri
options:
  model: "openai/whisper-large-v3-turbo"
  device: "GPU"
schema:
  model: str
  device: str
