name: "OpenVINO Whisper Large-Turbo"
description: "OpenVINO accelerated Whisper for LattePanda using Wyoming Protocol"
version: "2.0.1"
slug: "openvino_whisper"
arch:
  - amd64
startup: services
boot: auto
ports:
  10300/tcp: 10300
options:
  model: "large-v3-turbo"
  language: "en"
schema:
  model: "str"
  language: "str"
