name: "OpenVINO Whisper STT"
slug: "openvino_whisper"
description: "Intel OpenVINO accelerated Whisper STT"
version: "2.0.3"
startup: services
boot: auto
host_network: true
devices:
  - /dev/dri:/dev/dri
ports:
  10300/tcp: 10300
options:
  model: "OpenVINO/whisper-small-int8-ov"
  device: "AUTO"
schema:
  model: str
  device: str
