name: "OpenVINO Whisper STT"
slug: "openvino_whisper"
description: "Intel OpenVINO accelerated Whisper STT"
version: "1.1.1"
arch:
  - amd64
init: false
startup: services
boot: auto
discovery:
  - wyoming
devices:
  - /dev/dri:/dev/dri
options:
  model: "openai/whisper-large-v3-turbo"
  device: "CPU"
  language: "en"
schema:
  model: str
  device: str
  language: str
homeassistant: "2023.9.0"
