name: "OpenVINO Whisper STT"
slug: "openvino_whisper"
description: "Intel OpenVINO accelerated Whisper STT"
version: "2.1.0"
arch:
  - amd64
startup: services
boot: auto
host_network: true
ports:
  10300/tcp: 10300
options:
  model: "OpenVINO/whisper-small-int8-ov"
  device: "AUTO"
schema:
  model: str
  device: str
