name: "OpenVINO Whisper STT"
slug: "openvino_whisper"
description: "Intel OpenVINO accelerated Whisper STT"
version: "8.1.0"
arch:
  - amd64
startup: services
boot: auto
host_network: true
privileged:
  - SYS_ADMIN
devices:
  - /dev/dri:/dev/dri
discovery:
  - wyoming
ports:
  10300/tcp: 10300
options:
  model: "openai/whisper-large-v3-turbo"
  device: "GPU"
schema:
  model: str
  device: str
