name: "OpenVINO Whisper STT"
slug: "openvino_whisper"
description: "Intel OpenVINO accelerated Whisper STT"
version: "8.0.1"
arch:
  - amd64
startup: services
boot: auto
host_network: true
privileged:
  - SYS_ADMIN
group_add:
  - 44   # video
  - 100  # users
  - 107  # render (Standard for Iris Xe)
  - 109  # render (Alternative ID)
devices:
  - /dev/dri:/dev/dri
ports:
  10300/tcp: 10300
options:
  model: "openai/whisper-large-v3-turbo"
  device: "GPU"
schema:
  model: str
  device: str
