name: "OpenVINO Whisper Large-Turbo"
description: "OpenVINO accelerated Whisper Large-v3-Turbo for LattePanda"
version: "1.1.0"
slug: "openvino_whisper"
arch:
  - amd64
init: false
ports:
  10300/tcp: 10300
options:
  model: "bweng/whisper-large-v3-turbo-int8-ov" # Pre-optimized OpenVINO model
  language: "en"
schema:
  model: "str"
  language: "str"
